Insert into faculty(Id, FirstName, LastName,PHD_MS, Department, ContactEmail, Office) Values 
('1','Suhair','Amer', 'Ph.D', 'CS', 'samer@semo.edu', 'Dempster Hall 264'),
('2','Waleed', 'Amer', 'MS', 'CS', 'wamer@semo.edu', 'Dempster Hall 249'),
('3','Ethan', 'Chou', 'MS', 'CS', 'echou@semo.edu', 'Dempster Hall 021H'),
('4','Mario', 'Garcia', 'PhD', 'CS', 'mgarcia@semo.edu', 'Dempster 246C'),
('5','Mario', 'Guimaraes', 'PhD', 'CS', 'mguiaraes@semo.edu', 'Dempster Hall 021A'),
('6','Ali', 'Ihsan', 'MS', 'CS', 'ialo@semo.edu', 'Dempster Hall 230'),
('7','Art', 'Kazmierczak', 'Phd', 'CS', 'akazmierczak@semo.edu', 'Dempster Hall 021J'),
('8','George', 'Li', 'PhD', 'CS', 'zli2@semo.edu', 'Dempster Hall 214'),
('9','Xiaoming', 'Liu', 'Phd', 'CS', 'xliu@semo.edu', 'Dempster Hall 021C'),
('10','Ziping', 'Liu', 'PHD', 'CS', 'zliu@semo.edu', 'Dempster Hall 209'),
('11','Bob', 'Lowe', 'PHD', 'CS', 'rlowe@semo.edu', 'Dempster Hall 213'),
('12','Reshmi', 'Mitra', 'PHD', 'CS', 'rmitra@semo.edu', 'Dempster Hall 246e'),
('13','Carole', 'Pfeiffer', 'MS', 'CS', 'cpfeiffer@semo.edu', 'Dempster Hall 021D'),
('14','Maureen', 'Richards', 'N/A', 'CS', 'mrichards@semo.edu', 'Dempster Hall 021A'),
('15','Indranil', 'Roy', 'N/A', 'MS', 'iroy@semo.edu', 'Dempster Hall 021F'),
('16','Paul', 'Setzer', 'MS', 'CS', 'pbsetzer@semo.edu', 'Dempster Hall 021A'),
('17','Juefei', 'Yuan', 'MS', 'CS', 'jyuan@semo.edu', 'Dempster Hall 021G'),
('18','Chuck','McAllister', 'PHD', 'Marketing', 'cdmcallister@semo.edu', 'Dempster Hall 225'),
('19','David', 'Miller', 'MS', 'Technology','Noemailpresently', 'Polytech 213H'),
('20','Cynthia', 'Calongne', 'MS', 'CS', 'cmcalongne@semo.edu', 'Dempster Hall 021A'),
('21','Terri', 'Smith', 'MS', 'CS', 'tcsmith@semo.edu', 'Dempster Hall 021A')